name: Build and Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Run application
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        ENCRYPTION_IV: ${{ secrets.ENCRYPTION_IV }}
      run: dotnet run --project <YourProjectName>
